on: [push]

jobs:
  campaigns_run_job:
    runs-on: ubuntu-latest
    environment: test
    name: Test
    steps:
      - name: Campaigns run
        id: campaigns_run
        uses: mbouchotsuricate/campaigns_run_action@1.0.3
        with:
          email: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          campaign_ids: ${{ vars.CAMPAIGN_IDS }}
