on:
    - [push]
    - workflow_dispatch

jobs:
  campaigns_run_job:
    runs-on: ubuntu-latest
    environment: test
    name: Test
    steps:
      - name: Campaigns run
        id: campaigns_run
        uses: gurvan429/campaigns_run_action_test@1.0.4
        with:
          email: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          campaign_ids: ${{ vars.CAMPAIGN_IDS }}
