on: [push]

jobs:
  campaigns_run_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Campaigns run
        id: campaigns_run
        uses: mbouchotsuricate/campaigns_run_action@1.0.0
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          campaign_ids: ${{ env.CAMPAIGN_IDS }}
